export const START_GET_LIST_APPOINTMENT = 'START_GET_LIST_APPOINTMENT';
export const GET_LIST_APPOINTMENT_SUCCESS = 'GET_LIST_APPOINTMENT_SUCCESS';
export const GET_LIST_APPOINTMENT_FAILED = 'GET_LIST_APPOINTMENT_FAILED';
