export const START_BOOKING = 'START_BOOKING';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAILED = 'BOOKING_FAILED';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const START_GET_BOOKED = 'START_GET_BOOKED';
export const GET_BOOKED_SUCCESS = 'GET_BOOKED_SUCCESS';
export const GET_BOOKED_FAILED = 'GET_BOOKED_FAILED';

export const START_DELETE_BOOKED = 'START_DELETE_BOOKED';
export const DELETE_BOOKED_SUCCESS = 'DELETE_BOOKED_SUCCESS';
export const DELETE_BOOKED_FAILED = 'DELETE_BOOKED_FAILED';
