export const START_GET_LIST_SERVICE = 'START_GET_LIST_SERVICE';
export const GET_LIST_SERVICE = 'GET_LIST_SERVICE';
export const GET_LIST_SERVICE_SUCCESS = 'GET_LIST_SERVICE_SUCCESS';
export const GET_LIST_SERVICE_FAILED = 'GET_LIST_SERVICE_FAILED';

export const BOOK_SERVICE = 'BOOK_SERVICE';
